[package]
name = "r2emu"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
fern = "0.7.1"
log = "0.4.28"
regex = "1.12.2"
rand = "0.8"

[build-dependencies]
regex = "1.12.2"
